function output = clean_signal( input )
%CLEAN_SIGNAL Cleans the signal (preconditioning)
%   This is the function that will pre-process the signal so that detection
%   will be easier: frequency filter, noise-reduction...
    
    %% IN PROGRESS

    Fs=96e3; % 96 KHz
    
        % hydrophone signal is not zero mean :0
        signal1 = input - mean(input);

        % Just looking for minke whales
        % Band-pass filter
        % Generated by MATLAB(R) 8.1 and the DSP System Toolbox 8.4.
        % Generated on: 22-Nov-2013 14:26:55
        % Chebyshev Type I Bandpass filter designed using FDESIGN.BANDPASS.
        % All frequency values are in Hz.
        Fs = 96000;  % Sampling Frequency
        N      = 50;     % Order
        Fpass1 = 1000;   % First Passband Frequency
        Fpass2 = 12000;  % Second Passband Frequency
        Apass  = 1;      % Passband Ripple (dB)
        % Construct an FDESIGN object and call its CHEBY1 method.
        h  = fdesign.bandpass('N,Fp1,Fp2,Ap', N, Fpass1, Fpass2, Apass, Fs);
        Hd = design(h, 'cheby1');
        signal3 = sosfilt(Hd.sosMatrix,signal1);
        
        
        %% Percentile noise substraction
        
    output=signal3;


end

