function filter = build_filter()
% BUILD_FILTER returns a filter designed to bandpass minke whale sounds
    
    %  FILTRO ENTRE 1-12 Khz

    % Just looking for minke whales
    % Band-pass filter
    % Generated by MATLAB(R) 8.1 and the DSP System Toolbox 8.4.
    % Generated on: 22-Nov-2013 14:26:55
    % Chebyshev Type I Bandpass filter designed using FDESIGN.BANDPASS.
    % All frequency values are in Hz.
    Fs     = 96e3; % Sampling Frequency
    N      = 50;    % Order
    Fpass1 = 1e3;	% First Passband Frequency
    Fpass2 = 12e3;  % Second Passband Frequency
    Apass  = 1;     % Passband Ripple (dB)
    
    % Construct an FDESIGN object and call its CHEBY1 method.
    h  = fdesign.bandpass('N,Fp1,Fp2,Ap', N, Fpass1, Fpass2, Apass, Fs);
    filter = design(h, 'cheby1');
    
    % DEBUG: visualize the frequency response of the filter
    global DEBUG
    if ~isempty(DEBUG) && DEBUG
        fvtool(filter);
    end
end
