function output = filter_passband( input )
    %% FILTER PASS-BAND
    %  FILTRO ENTRE 1-12 Khz

    Fs=96e3; % 96 KHzs

    % Just looking for minke whales
    % Band-pass filter
    % Generated by MATLAB(R) 8.1 and the DSP System Toolbox 8.4.
    % Generated on: 22-Nov-2013 14:26:55
    % Chebyshev Type I Bandpass filter designed using FDESIGN.BANDPASS.
    % All frequency values are in Hz.
    Fs = 96000;  % Sampling Frequency
    N      = 50;     % Order
    Fpass1 = 1e3;   % First Passband Frequency
    Fpass2 = 12e3;  % Second Passband Frequency
    Apass  = 1;      % Passband Ripple (dB)
    
    % Construct an FDESIGN object and call its CHEBY1 method.
    h  = fdesign.bandpass('N,Fp1,Fp2,Ap', N, Fpass1, Fpass2, Apass, Fs);
    Hd = design(h, 'cheby1');
    
    output = sosfilt(Hd.sosMatrix,input);
    
    % DEBUG: visualize the frequency response of the filter
    % fvtool(Hd);
    
end