function plot3Dsensors()
%PLOT3DSENSORS Plots the position of the sensors in the 3D space

    % [X Y Z] location of each sensor in km.
    sensors = sensors_position()/1000; % = [X_1 Y_1 Y_1;
                                       %    X_2 Y_2 Y_2;
                                       %    ...]

    figure;
    hold on;
    
    % plot sensors positions as red squares
    plot3(sensors(:,1),sensors(:,2),sensors(:,3),...
        'rs','MarkerSize',15);
    
    % indications of sensor numbers
    for i=1:7
        text(sensors(i,1),sensors(i,2),sensors(i,3),...
            num2str(i));
    end
    
    % beautify
    xlabel('x [km]'); ylabel('y [km]'); zlabel('z [km]');
    title('Location of PMRF hydrophpnes (Kauai, Hawai)')
    axis tight    
    view(70,30);
    
    % limits (aristas)
    plot3(get(gca,'XLim'),...
        min(get(gca,'YLim'))*ones(1,2),...
        min(get(gca,'ZLim'))*ones(1,2),...
        'k')
    plot3(get(gca,'XLim'),...
        max(get(gca,'YLim'))*ones(1,2),...
        min(get(gca,'ZLim'))*ones(1,2),...
        'k')
    plot3(max(get(gca,'XLim'))*ones(1,2),...
        get(gca,'YLim'),...
        min(get(gca,'ZLim'))*ones(1,2),...
        'k')
    plot3(min(get(gca,'XLim'))*ones(1,2),...
        get(gca,'YLim'),...
        min(get(gca,'ZLim'))*ones(1,2),...
        'k')
    plot3(min(get(gca,'XLim'))*ones(1,2),...
        max(get(gca,'YLim'))*ones(1,2),...
        get(gca,'ZLim'),...
        'k')
    plot3(min(get(gca,'XLim'))*ones(1,2),...
        min(get(gca,'YLim'))*ones(1,2),...
        get(gca,'ZLim'),...
        'k')
    plot3(max(get(gca,'XLim'))*ones(1,2),...
        min(get(gca,'YLim'))*ones(1,2),...
        get(gca,'ZLim'),...
        'k')
    plot3(max(get(gca,'XLim'))*ones(1,2),...
        max(get(gca,'YLim'))*ones(1,2),...
        get(gca,'ZLim'),...
        'k')
    plot3(get(gca,'XLim'),...
        min(get(gca,'YLim'))*ones(1,2),...
        max(get(gca,'ZLim'))*ones(1,2),...
        'k')
    plot3(get(gca,'XLim'),...
        max(get(gca,'YLim'))*ones(1,2),...
        max(get(gca,'ZLim'))*ones(1,2),...
        'k')
    plot3(min(get(gca,'XLim'))*ones(1,2),...
        get(gca,'YLim'),...
        max(get(gca,'ZLim'))*ones(1,2),...
        'k')
    plot3(max(get(gca,'XLim'))*ones(1,2),...
        get(gca,'YLim'),...
        max(get(gca,'ZLim'))*ones(1,2),...
        'k')
    

end

